/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AttemptId = bigint;
export interface CoachingNote {
  'id' : NoteId,
  'content' : string,
  'studentId' : StudentId,
  'subject' : string,
  'teacherId' : TeacherId,
  'timestamp' : Timestamp,
}
export interface CreateLessonRequest {
  'title' : string,
  'content' : string,
  'subject' : string,
  'language' : Language,
  'gradeLevel' : Grade,
}
export interface CreateNoteRequest {
  'content' : string,
  'studentId' : StudentId,
  'subject' : string,
  'teacherId' : TeacherId,
}
export interface CreateQuizRequest {
  'title' : string,
  'subject' : string,
  'gradeLevel' : Grade,
  'questions' : Array<Question>,
}
export interface CreateStudentRequest {
  'languagePreference' : Language,
  'name' : string,
  'grade' : Grade,
}
export interface CreateTeacherRequest { 'name' : string }
export type Grade = { 'lkg' : null } |
  { 'ukg' : null } |
  { 'std1' : null } |
  { 'std2' : null } |
  { 'std3' : null } |
  { 'std4' : null } |
  { 'std5' : null } |
  { 'std6' : null } |
  { 'std7' : null } |
  { 'std8' : null } |
  { 'std9' : null } |
  { 'std10' : null };
export type Language = { 'hindi' : null } |
  { 'odia' : null } |
  { 'english' : null };
export interface Lesson {
  'id' : LessonId,
  'title' : string,
  'content' : string,
  'subject' : string,
  'createdAt' : Timestamp,
  'language' : Language,
  'gradeLevel' : Grade,
}
export type LessonId = bigint;
export type NoteId = bigint;
export type ProgressFlag = { 'red' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export interface Question {
  'id' : QuestionId,
  'text' : string,
  'correctAnswer' : string,
  'questionType' : QuestionType,
  'options' : Array<string>,
}
export type QuestionId = bigint;
export type QuestionType = { 'shortAnswer' : null } |
  { 'multipleChoice' : null };
export interface Quiz {
  'id' : QuizId,
  'title' : string,
  'subject' : string,
  'createdAt' : Timestamp,
  'gradeLevel' : Grade,
  'questions' : Array<Question>,
}
export interface QuizAttempt {
  'id' : AttemptId,
  'studentId' : StudentId,
  'answers' : Array<string>,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : Timestamp,
  'quizId' : QuizId,
}
export type QuizId = bigint;
export interface Student {
  'id' : StudentId,
  'languagePreference' : Language,
  'name' : string,
  'createdAt' : Timestamp,
  'grade' : Grade,
}
export type StudentId = bigint;
export interface StudentProgress {
  'studentId' : StudentId,
  'flag' : ProgressFlag,
  'latestAttempts' : Array<QuizAttempt>,
  'latestScores' : Array<bigint>,
}
export interface SubmitAttemptRequest {
  'studentId' : StudentId,
  'answers' : Array<string>,
  'quizId' : QuizId,
}
export interface Teacher {
  'id' : TeacherId,
  'principal' : Principal,
  'name' : string,
}
export type TeacherId = bigint;
export type Timestamp = bigint;
export interface _SERVICE {
  'addCoachingNote' : ActorMethod<[CreateNoteRequest], CoachingNote>,
  'createLesson' : ActorMethod<[CreateLessonRequest], Lesson>,
  'createQuiz' : ActorMethod<[CreateQuizRequest], Quiz>,
  'createStudent' : ActorMethod<[CreateStudentRequest], Student>,
  'createTeacher' : ActorMethod<[CreateTeacherRequest], Teacher>,
  'getAttemptDetail' : ActorMethod<[AttemptId], [] | [QuizAttempt]>,
  'getCoachingNotesForStudent' : ActorMethod<[StudentId], Array<CoachingNote>>,
  'getLessonsByGrade' : ActorMethod<[Grade], Array<Lesson>>,
  'getQuiz' : ActorMethod<[QuizId], [] | [Quiz]>,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getStudentAttempts' : ActorMethod<[StudentId], Array<QuizAttempt>>,
  'getStudentProgress' : ActorMethod<[StudentId], StudentProgress>,
  'getTeacher' : ActorMethod<[TeacherId], [] | [Teacher]>,
  'listQuizzesByGrade' : ActorMethod<[Grade], Array<Quiz>>,
  'listStudents' : ActorMethod<[[] | [Grade]], Array<Student>>,
  'submitQuizAttempt' : ActorMethod<[SubmitAttemptRequest], QuizAttempt>,
  'updateStudentLanguage' : ActorMethod<[StudentId, Language], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];