/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StudentId = IDL.Nat;
export const TeacherId = IDL.Nat;
export const CreateNoteRequest = IDL.Record({
  'content' : IDL.Text,
  'studentId' : StudentId,
  'subject' : IDL.Text,
  'teacherId' : TeacherId,
});
export const NoteId = IDL.Nat;
export const Timestamp = IDL.Int;
export const CoachingNote = IDL.Record({
  'id' : NoteId,
  'content' : IDL.Text,
  'studentId' : StudentId,
  'subject' : IDL.Text,
  'teacherId' : TeacherId,
  'timestamp' : Timestamp,
});
export const Language = IDL.Variant({
  'hindi' : IDL.Null,
  'odia' : IDL.Null,
  'english' : IDL.Null,
});
export const Grade = IDL.Variant({
  'lkg' : IDL.Null,
  'ukg' : IDL.Null,
  'std1' : IDL.Null,
  'std2' : IDL.Null,
  'std3' : IDL.Null,
  'std4' : IDL.Null,
  'std5' : IDL.Null,
  'std6' : IDL.Null,
  'std7' : IDL.Null,
  'std8' : IDL.Null,
  'std9' : IDL.Null,
  'std10' : IDL.Null,
});
export const CreateLessonRequest = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'language' : Language,
  'gradeLevel' : Grade,
});
export const LessonId = IDL.Nat;
export const Lesson = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : Timestamp,
  'language' : Language,
  'gradeLevel' : Grade,
});
export const QuestionId = IDL.Nat;
export const QuestionType = IDL.Variant({
  'shortAnswer' : IDL.Null,
  'multipleChoice' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : QuestionId,
  'text' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionType' : QuestionType,
  'options' : IDL.Vec(IDL.Text),
});
export const CreateQuizRequest = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'gradeLevel' : Grade,
  'questions' : IDL.Vec(Question),
});
export const QuizId = IDL.Nat;
export const Quiz = IDL.Record({
  'id' : QuizId,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : Timestamp,
  'gradeLevel' : Grade,
  'questions' : IDL.Vec(Question),
});
export const CreateStudentRequest = IDL.Record({
  'languagePreference' : Language,
  'name' : IDL.Text,
  'grade' : Grade,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'languagePreference' : Language,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'grade' : Grade,
});
export const CreateTeacherRequest = IDL.Record({ 'name' : IDL.Text });
export const Teacher = IDL.Record({
  'id' : TeacherId,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
});
export const AttemptId = IDL.Nat;
export const QuizAttempt = IDL.Record({
  'id' : AttemptId,
  'studentId' : StudentId,
  'answers' : IDL.Vec(IDL.Text),
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Timestamp,
  'quizId' : QuizId,
});
export const ProgressFlag = IDL.Variant({
  'red' : IDL.Null,
  'green' : IDL.Null,
  'yellow' : IDL.Null,
});
export const StudentProgress = IDL.Record({
  'studentId' : StudentId,
  'flag' : ProgressFlag,
  'latestAttempts' : IDL.Vec(QuizAttempt),
  'latestScores' : IDL.Vec(IDL.Nat),
});
export const SubmitAttemptRequest = IDL.Record({
  'studentId' : StudentId,
  'answers' : IDL.Vec(IDL.Text),
  'quizId' : QuizId,
});

export const idlService = IDL.Service({
  'addCoachingNote' : IDL.Func([CreateNoteRequest], [CoachingNote], []),
  'createLesson' : IDL.Func([CreateLessonRequest], [Lesson], []),
  'createQuiz' : IDL.Func([CreateQuizRequest], [Quiz], []),
  'createStudent' : IDL.Func([CreateStudentRequest], [Student], []),
  'createTeacher' : IDL.Func([CreateTeacherRequest], [Teacher], []),
  'getAttemptDetail' : IDL.Func([AttemptId], [IDL.Opt(QuizAttempt)], ['query']),
  'getCoachingNotesForStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(CoachingNote)],
      ['query'],
    ),
  'getLessonsByGrade' : IDL.Func([Grade], [IDL.Vec(Lesson)], ['query']),
  'getQuiz' : IDL.Func([QuizId], [IDL.Opt(Quiz)], ['query']),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getStudentAttempts' : IDL.Func(
      [StudentId],
      [IDL.Vec(QuizAttempt)],
      ['query'],
    ),
  'getStudentProgress' : IDL.Func([StudentId], [StudentProgress], ['query']),
  'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(Teacher)], ['query']),
  'listQuizzesByGrade' : IDL.Func([Grade], [IDL.Vec(Quiz)], ['query']),
  'listStudents' : IDL.Func([IDL.Opt(Grade)], [IDL.Vec(Student)], ['query']),
  'submitQuizAttempt' : IDL.Func([SubmitAttemptRequest], [QuizAttempt], []),
  'updateStudentLanguage' : IDL.Func([StudentId, Language], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StudentId = IDL.Nat;
  const TeacherId = IDL.Nat;
  const CreateNoteRequest = IDL.Record({
    'content' : IDL.Text,
    'studentId' : StudentId,
    'subject' : IDL.Text,
    'teacherId' : TeacherId,
  });
  const NoteId = IDL.Nat;
  const Timestamp = IDL.Int;
  const CoachingNote = IDL.Record({
    'id' : NoteId,
    'content' : IDL.Text,
    'studentId' : StudentId,
    'subject' : IDL.Text,
    'teacherId' : TeacherId,
    'timestamp' : Timestamp,
  });
  const Language = IDL.Variant({
    'hindi' : IDL.Null,
    'odia' : IDL.Null,
    'english' : IDL.Null,
  });
  const Grade = IDL.Variant({
    'lkg' : IDL.Null,
    'ukg' : IDL.Null,
    'std1' : IDL.Null,
    'std2' : IDL.Null,
    'std3' : IDL.Null,
    'std4' : IDL.Null,
    'std5' : IDL.Null,
    'std6' : IDL.Null,
    'std7' : IDL.Null,
    'std8' : IDL.Null,
    'std9' : IDL.Null,
    'std10' : IDL.Null,
  });
  const CreateLessonRequest = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'language' : Language,
    'gradeLevel' : Grade,
  });
  const LessonId = IDL.Nat;
  const Lesson = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : Timestamp,
    'language' : Language,
    'gradeLevel' : Grade,
  });
  const QuestionId = IDL.Nat;
  const QuestionType = IDL.Variant({
    'shortAnswer' : IDL.Null,
    'multipleChoice' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : QuestionId,
    'text' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionType' : QuestionType,
    'options' : IDL.Vec(IDL.Text),
  });
  const CreateQuizRequest = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'gradeLevel' : Grade,
    'questions' : IDL.Vec(Question),
  });
  const QuizId = IDL.Nat;
  const Quiz = IDL.Record({
    'id' : QuizId,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : Timestamp,
    'gradeLevel' : Grade,
    'questions' : IDL.Vec(Question),
  });
  const CreateStudentRequest = IDL.Record({
    'languagePreference' : Language,
    'name' : IDL.Text,
    'grade' : Grade,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'languagePreference' : Language,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'grade' : Grade,
  });
  const CreateTeacherRequest = IDL.Record({ 'name' : IDL.Text });
  const Teacher = IDL.Record({
    'id' : TeacherId,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
  });
  const AttemptId = IDL.Nat;
  const QuizAttempt = IDL.Record({
    'id' : AttemptId,
    'studentId' : StudentId,
    'answers' : IDL.Vec(IDL.Text),
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Timestamp,
    'quizId' : QuizId,
  });
  const ProgressFlag = IDL.Variant({
    'red' : IDL.Null,
    'green' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const StudentProgress = IDL.Record({
    'studentId' : StudentId,
    'flag' : ProgressFlag,
    'latestAttempts' : IDL.Vec(QuizAttempt),
    'latestScores' : IDL.Vec(IDL.Nat),
  });
  const SubmitAttemptRequest = IDL.Record({
    'studentId' : StudentId,
    'answers' : IDL.Vec(IDL.Text),
    'quizId' : QuizId,
  });
  
  return IDL.Service({
    'addCoachingNote' : IDL.Func([CreateNoteRequest], [CoachingNote], []),
    'createLesson' : IDL.Func([CreateLessonRequest], [Lesson], []),
    'createQuiz' : IDL.Func([CreateQuizRequest], [Quiz], []),
    'createStudent' : IDL.Func([CreateStudentRequest], [Student], []),
    'createTeacher' : IDL.Func([CreateTeacherRequest], [Teacher], []),
    'getAttemptDetail' : IDL.Func(
        [AttemptId],
        [IDL.Opt(QuizAttempt)],
        ['query'],
      ),
    'getCoachingNotesForStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(CoachingNote)],
        ['query'],
      ),
    'getLessonsByGrade' : IDL.Func([Grade], [IDL.Vec(Lesson)], ['query']),
    'getQuiz' : IDL.Func([QuizId], [IDL.Opt(Quiz)], ['query']),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getStudentAttempts' : IDL.Func(
        [StudentId],
        [IDL.Vec(QuizAttempt)],
        ['query'],
      ),
    'getStudentProgress' : IDL.Func([StudentId], [StudentProgress], ['query']),
    'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(Teacher)], ['query']),
    'listQuizzesByGrade' : IDL.Func([Grade], [IDL.Vec(Quiz)], ['query']),
    'listStudents' : IDL.Func([IDL.Opt(Grade)], [IDL.Vec(Student)], ['query']),
    'submitQuizAttempt' : IDL.Func([SubmitAttemptRequest], [QuizAttempt], []),
    'updateStudentLanguage' : IDL.Func([StudentId, Language], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };