/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Student {
    id: StudentId;
    languagePreference: Language;
    name: string;
    createdAt: Timestamp;
    grade: Grade;
}
export interface SubmitAttemptRequest {
    studentId: StudentId;
    answers: Array<string>;
    quizId: QuizId;
}
export type Timestamp = bigint;
export type NoteId = bigint;
export type AttemptId = bigint;
export type LessonId = bigint;
export interface CreateNoteRequest {
    content: string;
    studentId: StudentId;
    subject: string;
    teacherId: TeacherId;
}
export interface Quiz {
    id: QuizId;
    title: string;
    subject: string;
    createdAt: Timestamp;
    gradeLevel: Grade;
    questions: Array<Question>;
}
export type QuestionId = bigint;
export interface CreateTeacherRequest {
    name: string;
}
export interface Teacher {
    id: TeacherId;
    principal: Principal;
    name: string;
}
export type StudentId = bigint;
export type TeacherId = bigint;
export interface CreateStudentRequest {
    languagePreference: Language;
    name: string;
    grade: Grade;
}
export interface Lesson {
    id: LessonId;
    title: string;
    content: string;
    subject: string;
    createdAt: Timestamp;
    language: Language;
    gradeLevel: Grade;
}
export interface QuizAttempt {
    id: AttemptId;
    studentId: StudentId;
    answers: Array<string>;
    score: bigint;
    totalQuestions: bigint;
    timestamp: Timestamp;
    quizId: QuizId;
}
export interface CreateQuizRequest {
    title: string;
    subject: string;
    gradeLevel: Grade;
    questions: Array<Question>;
}
export interface StudentProgress {
    studentId: StudentId;
    flag: ProgressFlag;
    latestAttempts: Array<QuizAttempt>;
    latestScores: Array<bigint>;
}
export interface CoachingNote {
    id: NoteId;
    content: string;
    studentId: StudentId;
    subject: string;
    teacherId: TeacherId;
    timestamp: Timestamp;
}
export interface Question {
    id: QuestionId;
    text: string;
    correctAnswer: string;
    questionType: QuestionType;
    options: Array<string>;
}
export interface CreateLessonRequest {
    title: string;
    content: string;
    subject: string;
    language: Language;
    gradeLevel: Grade;
}
export type QuizId = bigint;
export enum Grade {
    lkg = "lkg",
    ukg = "ukg",
    std1 = "std1",
    std2 = "std2",
    std3 = "std3",
    std4 = "std4",
    std5 = "std5",
    std6 = "std6",
    std7 = "std7",
    std8 = "std8",
    std9 = "std9",
    std10 = "std10"
}
export enum Language {
    hindi = "hindi",
    odia = "odia",
    english = "english"
}
export enum ProgressFlag {
    red = "red",
    green = "green",
    yellow = "yellow"
}
export enum QuestionType {
    shortAnswer = "shortAnswer",
    multipleChoice = "multipleChoice"
}
export interface backendInterface {
    addCoachingNote(req: CreateNoteRequest): Promise<CoachingNote>;
    createLesson(req: CreateLessonRequest): Promise<Lesson>;
    createQuiz(req: CreateQuizRequest): Promise<Quiz>;
    createStudent(req: CreateStudentRequest): Promise<Student>;
    createTeacher(req: CreateTeacherRequest): Promise<Teacher>;
    getAttemptDetail(attemptId: AttemptId): Promise<QuizAttempt | null>;
    getCoachingNotesForStudent(studentId: StudentId): Promise<Array<CoachingNote>>;
    getLessonsByGrade(grade: Grade): Promise<Array<Lesson>>;
    getQuiz(id: QuizId): Promise<Quiz | null>;
    getStudent(id: StudentId): Promise<Student | null>;
    getStudentAttempts(studentId: StudentId): Promise<Array<QuizAttempt>>;
    getStudentProgress(studentId: StudentId): Promise<StudentProgress>;
    getTeacher(id: TeacherId): Promise<Teacher | null>;
    listQuizzesByGrade(grade: Grade): Promise<Array<Quiz>>;
    listStudents(gradeFilter: Grade | null): Promise<Array<Student>>;
    submitQuizAttempt(req: SubmitAttemptRequest): Promise<QuizAttempt>;
    updateStudentLanguage(id: StudentId, language: Language): Promise<boolean>;
}
import type { CreateLessonRequest as _CreateLessonRequest, CreateQuizRequest as _CreateQuizRequest, CreateStudentRequest as _CreateStudentRequest, Grade as _Grade, Language as _Language, Lesson as _Lesson, LessonId as _LessonId, ProgressFlag as _ProgressFlag, Question as _Question, QuestionId as _QuestionId, QuestionType as _QuestionType, Quiz as _Quiz, QuizAttempt as _QuizAttempt, QuizId as _QuizId, Student as _Student, StudentId as _StudentId, StudentProgress as _StudentProgress, Teacher as _Teacher, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCoachingNote(arg0: CreateNoteRequest): Promise<CoachingNote> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoachingNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoachingNote(arg0);
            return result;
        }
    }
    async createLesson(arg0: CreateLessonRequest): Promise<Lesson> {
        if (this.processError) {
            try {
                const result = await this.actor.createLesson(to_candid_CreateLessonRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Lesson_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLesson(to_candid_CreateLessonRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Lesson_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createQuiz(arg0: CreateQuizRequest): Promise<Quiz> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(to_candid_CreateQuizRequest_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Quiz_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(to_candid_CreateQuizRequest_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Quiz_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStudent(arg0: CreateStudentRequest): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(to_candid_CreateStudentRequest_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Student_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(to_candid_CreateStudentRequest_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Student_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTeacher(arg0: CreateTeacherRequest): Promise<Teacher> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeacher(arg0);
            return result;
        }
    }
    async getAttemptDetail(arg0: AttemptId): Promise<QuizAttempt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttemptDetail(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttemptDetail(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoachingNotesForStudent(arg0: StudentId): Promise<Array<CoachingNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachingNotesForStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachingNotesForStudent(arg0);
            return result;
        }
    }
    async getLessonsByGrade(arg0: Grade): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonsByGrade(to_candid_Grade_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonsByGrade(to_candid_Grade_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuiz(arg0: QuizId): Promise<Quiz | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: StudentId): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentAttempts(arg0: StudentId): Promise<Array<QuizAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentAttempts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentAttempts(arg0);
            return result;
        }
    }
    async getStudentProgress(arg0: StudentId): Promise<StudentProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProgress(arg0);
                return from_candid_StudentProgress_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProgress(arg0);
            return from_candid_StudentProgress_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacher(arg0: TeacherId): Promise<Teacher | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacher(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacher(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuizzesByGrade(arg0: Grade): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuizzesByGrade(to_candid_Grade_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuizzesByGrade(to_candid_Grade_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudents(arg0: Grade | null): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents(to_candid_opt_n41(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents(to_candid_opt_n41(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitQuizAttempt(arg0: SubmitAttemptRequest): Promise<QuizAttempt> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAttempt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAttempt(arg0);
            return result;
        }
    }
    async updateStudentLanguage(arg0: StudentId, arg1: Language): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentLanguage(arg0, to_candid_Language_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentLanguage(arg0, to_candid_Language_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Grade_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Grade): Grade {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Lesson_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Lesson {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ProgressFlag_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProgressFlag): ProgressFlag {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Quiz_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quiz): Quiz {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_StudentProgress_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProgress): StudentProgress {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizAttempt]): QuizAttempt | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quiz]): Quiz | null {
    return value.length === 0 ? null : from_candid_Quiz_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Teacher]): Teacher | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuizId;
    title: string;
    subject: string;
    createdAt: _Timestamp;
    gradeLevel: _Grade;
    questions: Array<_Question>;
}): {
    id: QuizId;
    title: string;
    subject: string;
    createdAt: Timestamp;
    gradeLevel: Grade;
    questions: Array<Question>;
} {
    return {
        id: value.id,
        title: value.title,
        subject: value.subject,
        createdAt: value.createdAt,
        gradeLevel: from_candid_Grade_n11(_uploadFile, _downloadFile, value.gradeLevel),
        questions: from_candid_vec_n22(_uploadFile, _downloadFile, value.questions)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuestionId;
    text: string;
    correctAnswer: string;
    questionType: _QuestionType;
    options: Array<string>;
}): {
    id: QuestionId;
    text: string;
    correctAnswer: string;
    questionType: QuestionType;
    options: Array<string>;
} {
    return {
        id: value.id,
        text: value.text,
        correctAnswer: value.correctAnswer,
        questionType: from_candid_QuestionType_n25(_uploadFile, _downloadFile, value.questionType),
        options: value.options
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    languagePreference: _Language;
    name: string;
    createdAt: _Timestamp;
    grade: _Grade;
}): {
    id: StudentId;
    languagePreference: Language;
    name: string;
    createdAt: Timestamp;
    grade: Grade;
} {
    return {
        id: value.id,
        languagePreference: from_candid_Language_n9(_uploadFile, _downloadFile, value.languagePreference),
        name: value.name,
        createdAt: value.createdAt,
        grade: from_candid_Grade_n11(_uploadFile, _downloadFile, value.grade)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: _StudentId;
    flag: _ProgressFlag;
    latestAttempts: Array<_QuizAttempt>;
    latestScores: Array<bigint>;
}): {
    studentId: StudentId;
    flag: ProgressFlag;
    latestAttempts: Array<QuizAttempt>;
    latestScores: Array<bigint>;
} {
    return {
        studentId: value.studentId,
        flag: from_candid_ProgressFlag_n37(_uploadFile, _downloadFile, value.flag),
        latestAttempts: value.latestAttempts,
        latestScores: value.latestScores
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LessonId;
    title: string;
    content: string;
    subject: string;
    createdAt: _Timestamp;
    language: _Language;
    gradeLevel: _Grade;
}): {
    id: LessonId;
    title: string;
    content: string;
    subject: string;
    createdAt: Timestamp;
    language: Language;
    gradeLevel: Grade;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        subject: value.subject,
        createdAt: value.createdAt,
        language: from_candid_Language_n9(_uploadFile, _downloadFile, value.language),
        gradeLevel: from_candid_Grade_n11(_uploadFile, _downloadFile, value.gradeLevel)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hindi: null;
} | {
    odia: null;
} | {
    english: null;
}): Language {
    return "hindi" in value ? Language.hindi : "odia" in value ? Language.odia : "english" in value ? Language.english : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lkg: null;
} | {
    ukg: null;
} | {
    std1: null;
} | {
    std2: null;
} | {
    std3: null;
} | {
    std4: null;
} | {
    std5: null;
} | {
    std6: null;
} | {
    std7: null;
} | {
    std8: null;
} | {
    std9: null;
} | {
    std10: null;
}): Grade {
    return "lkg" in value ? Grade.lkg : "ukg" in value ? Grade.ukg : "std1" in value ? Grade.std1 : "std2" in value ? Grade.std2 : "std3" in value ? Grade.std3 : "std4" in value ? Grade.std4 : "std5" in value ? Grade.std5 : "std6" in value ? Grade.std6 : "std7" in value ? Grade.std7 : "std8" in value ? Grade.std8 : "std9" in value ? Grade.std9 : "std10" in value ? Grade.std10 : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shortAnswer: null;
} | {
    multipleChoice: null;
}): QuestionType {
    return "shortAnswer" in value ? QuestionType.shortAnswer : "multipleChoice" in value ? QuestionType.multipleChoice : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
}): ProgressFlag {
    return "red" in value ? ProgressFlag.red : "green" in value ? ProgressFlag.green : "yellow" in value ? ProgressFlag.yellow : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lesson>): Array<Lesson> {
    return value.map((x)=>from_candid_Lesson_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quiz>): Array<Quiz> {
    return value.map((x)=>from_candid_Quiz_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n29(_uploadFile, _downloadFile, x));
}
function to_candid_CreateLessonRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateLessonRequest): _CreateLessonRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateQuizRequest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateQuizRequest): _CreateQuizRequest {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_CreateStudentRequest_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateStudentRequest): _CreateStudentRequest {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_Grade_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Grade): _Grade {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Question_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Grade | null): [] | [_Grade] {
    return value === null ? candid_none() : candid_some(to_candid_Grade_n5(_uploadFile, _downloadFile, value));
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    subject: string;
    gradeLevel: Grade;
    questions: Array<Question>;
}): {
    title: string;
    subject: string;
    gradeLevel: _Grade;
    questions: Array<_Question>;
} {
    return {
        title: value.title,
        subject: value.subject,
        gradeLevel: to_candid_Grade_n5(_uploadFile, _downloadFile, value.gradeLevel),
        questions: to_candid_vec_n15(_uploadFile, _downloadFile, value.questions)
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: QuestionId;
    text: string;
    correctAnswer: string;
    questionType: QuestionType;
    options: Array<string>;
}): {
    id: _QuestionId;
    text: string;
    correctAnswer: string;
    questionType: _QuestionType;
    options: Array<string>;
} {
    return {
        id: value.id,
        text: value.text,
        correctAnswer: value.correctAnswer,
        questionType: to_candid_QuestionType_n18(_uploadFile, _downloadFile, value.questionType),
        options: value.options
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    subject: string;
    language: Language;
    gradeLevel: Grade;
}): {
    title: string;
    content: string;
    subject: string;
    language: _Language;
    gradeLevel: _Grade;
} {
    return {
        title: value.title,
        content: value.content,
        subject: value.subject,
        language: to_candid_Language_n3(_uploadFile, _downloadFile, value.language),
        gradeLevel: to_candid_Grade_n5(_uploadFile, _downloadFile, value.gradeLevel)
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    languagePreference: Language;
    name: string;
    grade: Grade;
}): {
    languagePreference: _Language;
    name: string;
    grade: _Grade;
} {
    return {
        languagePreference: to_candid_Language_n3(_uploadFile, _downloadFile, value.languagePreference),
        name: value.name,
        grade: to_candid_Grade_n5(_uploadFile, _downloadFile, value.grade)
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): {
    shortAnswer: null;
} | {
    multipleChoice: null;
} {
    return value == QuestionType.shortAnswer ? {
        shortAnswer: null
    } : value == QuestionType.multipleChoice ? {
        multipleChoice: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    hindi: null;
} | {
    odia: null;
} | {
    english: null;
} {
    return value == Language.hindi ? {
        hindi: null
    } : value == Language.odia ? {
        odia: null
    } : value == Language.english ? {
        english: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Grade): {
    lkg: null;
} | {
    ukg: null;
} | {
    std1: null;
} | {
    std2: null;
} | {
    std3: null;
} | {
    std4: null;
} | {
    std5: null;
} | {
    std6: null;
} | {
    std7: null;
} | {
    std8: null;
} | {
    std9: null;
} | {
    std10: null;
} {
    return value == Grade.lkg ? {
        lkg: null
    } : value == Grade.ukg ? {
        ukg: null
    } : value == Grade.std1 ? {
        std1: null
    } : value == Grade.std2 ? {
        std2: null
    } : value == Grade.std3 ? {
        std3: null
    } : value == Grade.std4 ? {
        std4: null
    } : value == Grade.std5 ? {
        std5: null
    } : value == Grade.std6 ? {
        std6: null
    } : value == Grade.std7 ? {
        std7: null
    } : value == Grade.std8 ? {
        std8: null
    } : value == Grade.std9 ? {
        std9: null
    } : value == Grade.std10 ? {
        std10: null
    } : value;
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Question>): Array<_Question> {
    return value.map((x)=>to_candid_Question_n16(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
